---
- hosts: nginx
  become: yes
  become_method: sudo 
  tasks: 

  - name: Install nginx
     yum: 
      name: nginx
      state: latest 
      update_cache: yes
    notify: started 


  handlers:

  - name: start nginx 
    service:
       name: nginx 
       state: latest
