---
- name: check nginx status 
  hosts: nginx 
  tasks: 

  - name: check_nginx 
    ansible.builtin.shell:
        cmd: systemctl status nginx 
    register: result


  - name: Display result 
    debug: 
      msg:"{{result.stdout_lines}}"
      