---
- hosts: web 
  become: yes
  become_method: sudo 
  tasks:

  - name: stop nginx 
    service:
      name: nginx
      state: stopped

  - name: uninstall nginx 
    yum: 
     name: nginx 
     state: absent 
     