---
- hosts: nginx
  become: yes
  become_method: sudo 
  tasks:

  - name: Install nginx 
      yum:
       name: nginx
       state: latest
       update_cache: yes
     when: ansible_facsts['os_family'] == "RHEL"

  - name: start nginx
    service:
       name: nginx
       state: started
     when: ansible_facts['os_family'] == "RHEL"

     
  